### PR TITLE
Fix #26 - RAMInBytes Bug

### LINKED ISSUE #26: RAMInBytes not parsing strings returned by BytesSize
Example:
```
units.RAMInBytes("32GiB")
```
This returns an error...

### PR DESCRIPTION
**Pull request by FlorinAsavoaie**
RAMInBytes wasn't able to parse the output of BytesSize until now.

Signed-off-by: Florin Asavoaie <FlorinAsavoaie@users.noreply.github.com>

### CODE REVIEW

**Comment by FlorinAsavoaie** [comment]
@thaJeztah Not sure who can look at this, pinging you so that someone is aware about the PR.

File: size_test.go [hunk 1]
```diff
@@ -116,6 +116,8 @@ func TestRAMInBytes(t *testing.T) {
 	assertSuccessEquals(t, 32*KiB, RAMInBytes, "32K")
 	assertSuccessEquals(t, 32*KiB, RAMInBytes, "32kb")
 	assertSuccessEquals(t, 32*KiB, RAMInBytes, "32Kb")
+	assertSuccessEquals(t, 32*KiB, RAMInBytes, "32Kib")
+	assertSuccessEquals(t, 32*KiB, RAMInBytes, "32KIB")
```
Comment (thaJeztah) [inline size_test.go]: Looking at these, I wonder if it's correct that we treat `kB`, `KiB` and `KB` equal; from https://en.wikipedia.org/wiki/Kilobyte

screen shot 2017-12-21 at 18 38 01

32 KB == 32 KiB == 32768 byte, but 32kB == 32000 byte

Comment (thaJeztah) [reply size_test.go]: Actually, wondering if I'm reading `KB` (JEDEC) correctly in that table, so please double-check 😅

Comment (FlorinAsavoaie) [reply size_test.go]: Well, that was, obviously, already there. What I added *should* be the correct behavior imho. However, I wonder how many things will break if we decide to parse it somehow around.

Also, on the other hand, there's no function here to make a difference between KB and KiB, it just depends on what function does the user of the library call.

Comment (thaJeztah) [reply size_test.go]: Yes, I noticed it was there 😞 not sure what's best; perhaps we need additional functions

Comment (FlorinAsavoaie) [reply size_test.go]: Well, I don't think this module is organized in such a way to properly support the standards. I'd rather go for a rebuild of this module (go-units2 or go-standard-units :D) and organize the functions something like ReadHumanSizeBinary which properly parses IEC and JEDEC, then ReadHumanSizeDecimal which properly parses metric data. Also organize those maps and regexes per "Metric/Decimal" and "Binary/IEC/JEDEC".

My guess is that it would break a lot of stuff because these conventions are badly used all around.

Until then, would you think this is a blocker to merge this?

Comment (thaJeztah) [reply size_test.go]: Agreed, this change doesn't make things worse, so don't see a reason to not go ahead.

Let me know if you're interested in a follow up for those things though!
